services:
  app:
    build:
      context: ./  # Собираем образ из текущей директории
      dockerfile: Dockerfile
    container_name: programwithgio-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www  # Монтируем всю папку с проектом

  nginx:
    image: nginx:1.19-alpine
    container_name: programwithgio-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www  # Монтируем всю папку с проектом в nginx
      - ./nginx:/etc/nginx/conf.d  # nginx конфигурации
